name: build program

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '!*'
      
jobs:
  job1:
    name: pyinstall-build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          choco install zip
      
      - name: install pyinstaller
        run: |
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller -F build.spec
          cp -r init_conf dist/
          zip -r output.zip dist
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: pyinstall(exe)
          path: dist/