name: build program

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '!*'
      
jobs:
  job1:
    name: pyinstall-build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install zip
        run: |
          choco install zip
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: install pyinstaller
        run: |
          pip install pyinstaller
          pip uninstall pathlib

      - name: Build Windows Executable
        run: |
          pyinstaller -F -w main.py
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: pyinstall(exe)
          path: dist/main.exe