name: build program

on: push

jobs:
  job1:
    name: Nuitka-build
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Disable Windows Defender
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $true

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        choco install zip
        
    - name: Build Windows Executable
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        standalone: true
        include-package: ${{ github.workspace }}/requirements.txt
        enable-plugins: pyqt6

    - name: look file 
      run: |
        dir
      
    - name: copy init_conf to dist
      run: |
        mkdir dist
        cp -r init_conf dist/init_conf
        cp build/main.exe dist/

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v2
      with:
        name: nuitka(exe)
        path: dist/
     
    - name: Upload Windows Executable - build
      uses: actions/upload-artifact@v2
      with:
        name: nuitka-build
        path: build/
  job2:
    name: pyinstall-build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          choco install zip
      
      - name: install pyinstaller
        run: |
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller -F -w main.py
          cp -r init_conf dist/
          zip -r output.zip dist
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: pyinstall(exe)
          path: dist/