name: build main

on:
  pull_request:
    types: [closed]
  

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Disable Windows Defender
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: abatilo/actions-poetry@v2
        with:
          - name: Install and configure Poetry
            uses: abatilo/actions-poetry@v2
            with:
              python-version: 3.9
              poetry-version: 1.3.2
          poetry-version: 1.3.2
      - name: Install dependencies
        run: |
          choco install zip
          

      - name: Build Windows Executable
        run: |
          poetry install
          C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\working-cif-service-NxTJ2SoF-py3.9\Scripts\python.exe -m pip uninstall pathlib -y
          poetry run pyinstaller -F -w main.py
          zip -r init_conf.zip ./init_conf
          mv init_conf.zip dist/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: Release ${{ github.event.pull_request.head.ref }}
          release_title: "CIF Service Release -${{ github.event.pull_request.title }}"
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      - name: Upload Windows Executable and init_conf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ${{ github.workspace }}/dist/main.exe
            ${{ github.workspace }}/dist/init_conf.zip
          asset_name: |
            main.exe
            init_conf.zip
          asset_content_type: |
            application/octet-stream
            application/zip

