name: nuitka build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        
    - name: Disable Windows Defender
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $true

    - name: Build Windows Executable
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        standalone: true
        enable-plugins: pyqt6
      
    - name: copy init_conf to dist
      run: |
        mkdir dist
        cp -r init_conf dist/
        cp build/main.exe dist/

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v2
      with:
        name: your_script
        path: dist/