name: build main

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Disable Windows Defender
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          choco install zip
          
      - name: Build Windows Executable
        run: |
          pip install pyinstaller
          pip uninstall pathlib
          pyinstaller -F -w main.py
          zip -r output.zip dist

      # 使用 softprops/action-gh-release 替换原有的创建和上传发布资产的步骤
      - name: Create and Upload Release
        if: github.event.pull_request.merged == true
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
